/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TmdbApi from "../../index.mjs";
/**
 * @example
 *     {}
 */
export interface AccountRatedMoviesRequest {
    page?: number;
    language?: string;
    sort_by?: TmdbApi.AccountRatedMoviesRequestSortBy;
}
