/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare const TmdbApiEnvironment: {
    readonly Default: "https://api.themoviedb.org";
};
export type TmdbApiEnvironment = typeof TmdbApiEnvironment.Default;
