/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface AccountFavoriteTvResponse {
    page?: number;
    results?: AccountFavoriteTvResponse.Results.Item[];
    total_pages?: number;
    total_results?: number;
}
export declare namespace AccountFavoriteTvResponse {
    type Results = Results.Item[];
    namespace Results {
        interface Item {
            adult?: boolean;
            backdrop_path?: string;
            genre_ids?: number[];
            id?: number;
            origin_country?: string[];
            original_language?: string;
            original_name?: string;
            overview?: string;
            popularity?: number;
            poster_path?: string;
            first_air_date?: string;
            name?: string;
            vote_average?: number;
            vote_count?: number;
        }
    }
}
