/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type AccountFavoriteMoviesRequestSortBy = "created_at.asc" | "created_at.desc";
export declare const AccountFavoriteMoviesRequestSortBy: {
    readonly CreatedAtAsc: "created_at.asc";
    readonly CreatedAtDesc: "created_at.desc";
};
