/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface AccountTvWatchlistResponse {
    page?: number;
    results?: AccountTvWatchlistResponse.Results.Item[];
    total_pages?: number;
    total_results?: number;
}
export declare namespace AccountTvWatchlistResponse {
    type Results = Results.Item[];
    namespace Results {
        interface Item {
            adult?: boolean;
            backdrop_path?: string;
            id?: number;
            name?: string;
            original_language?: string;
            original_name?: string;
            overview?: string;
            poster_path?: string;
            media_type?: string;
            genre_ids?: number[];
            popularity?: number;
            first_air_date?: string;
            vote_average?: number;
            vote_count?: number;
            origin_country?: string[];
        }
    }
}
