/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface AccountListsResponse {
    page?: number;
    results?: AccountListsResponse.Results.Item[];
    total_pages?: number;
    total_results?: number;
}
export declare namespace AccountListsResponse {
    type Results = Results.Item[];
    namespace Results {
        interface Item {
            account_object_id?: string;
            adult?: number;
            average_rating?: number;
            created_at?: string;
            description?: string;
            featured?: number;
            id?: number;
            iso_3166_1?: string;
            iso_639_1?: string;
            name?: string;
            number_of_items?: number;
            public?: number;
            revenue?: string;
            runtime?: number;
            sort_by?: number;
            updated_at?: string;
        }
    }
}
