"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AccountFavoriteTvRequestSortBy = void 0;
exports.AccountFavoriteTvRequestSortBy = {
    CreatedAtAsc: "created_at.asc",
    CreatedAtDesc: "created_at.desc",
};
