/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface ListItemStatusResponse {
    media_type?: string;
    success?: boolean;
    status_message?: string;
    id?: number;
    media_id?: number;
    status_code?: number;
}
