/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface ListClearResponse {
    items_deleted?: number;
    status_message?: string;
    id?: number;
    status_code?: number;
    success?: boolean;
}
