/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TmdbApi from "../../index.js";
/**
 * @example
 *     {}
 */
export interface AccountMovieWatchlistRequest {
    page?: number;
    language?: string;
    sort_by?: TmdbApi.AccountMovieWatchlistRequestSortBy;
}
