/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         RAW_BODY: "RAW_BODY"
 *     }
 */
export interface AuthCreateAccessTokenRequest {
    RAW_BODY: string;
}
