/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as TmdbApi from "../../index.js";
/**
 * @example
 *     {
 *         media_id: 1,
 *         media_type: ""
 *     }
 */
export interface ListItemStatusRequest {
    media_id: number;
    media_type: TmdbApi.ListItemStatusRequestMediaType;
}
