/**
 * This file was auto-generated by Fern from our API Definition.
 */
export const AccountMovieWatchlistRequestSortBy = {
    CreatedAtAsc: "created_at.asc",
    CreatedAtDesc: "created_at.desc",
};
