/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface ListUpdateItemsResponse {
    status_message?: string;
    results?: ListUpdateItemsResponse.Results.Item[];
    success?: boolean;
    status_code?: number;
}
export declare namespace ListUpdateItemsResponse {
    type Results = Results.Item[];
    namespace Results {
        interface Item {
            media_type?: string;
            media_id?: number;
            success?: boolean;
        }
    }
}
