"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TmdbApiEnvironment = void 0;
exports.TmdbApiEnvironment = {
    Default: "https://api.themoviedb.org",
};
