/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface AccountMovieRecommendationsResponse {
    page?: number;
    results?: AccountMovieRecommendationsResponse.Results.Item[];
    total_pages?: number;
    total_results?: number;
}
export declare namespace AccountMovieRecommendationsResponse {
    type Results = Results.Item[];
    namespace Results {
        interface Item {
            adult?: boolean;
            backdrop_path?: string;
            id?: number;
            title?: string;
            original_language?: string;
            original_title?: string;
            overview?: string;
            poster_path?: string;
            media_type?: string;
            genre_ids?: number[];
            popularity?: number;
            release_date?: string;
            video?: boolean;
            vote_average?: number;
            vote_count?: number;
        }
    }
}
