"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ListItemStatusRequestMediaType = void 0;
exports.ListItemStatusRequestMediaType = {
    Empty: "",
    Movie: "movie",
    Tv: "tv",
};
