/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface ListCreateResponse {
    status_message?: string;
    id?: number;
    success?: boolean;
    status_code?: number;
}
