/**
 * This file was auto-generated by Fern from our API Definition.
 */
export class TmdbApiTimeoutError extends Error {
    constructor(message) {
        super(message);
        Object.setPrototypeOf(this, TmdbApiTimeoutError.prototype);
    }
}
