/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type AccountRatedMoviesRequestSortBy = "created_at.asc" | "created_at.desc";
export declare const AccountRatedMoviesRequestSortBy: {
    readonly CreatedAtAsc: "created_at.asc";
    readonly CreatedAtDesc: "created_at.desc";
};
