/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface AccountFavoriteMoviesResponse {
    page?: number;
    results?: AccountFavoriteMoviesResponse.Results.Item[];
    total_pages?: number;
    total_results?: number;
}
export declare namespace AccountFavoriteMoviesResponse {
    type Results = Results.Item[];
    namespace Results {
        interface Item {
            adult?: boolean;
            backdrop_path?: string;
            genre_ids?: number[];
            id?: number;
            original_language?: string;
            original_title?: string;
            overview?: string;
            popularity?: number;
            poster_path?: string;
            release_date?: string;
            title?: string;
            video?: boolean;
            vote_average?: number;
            vote_count?: number;
        }
    }
}
