/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface AccountRatedMoviesResponse {
    page?: number;
    results?: AccountRatedMoviesResponse.Results.Item[];
    total_pages?: number;
    total_results?: number;
}
export declare namespace AccountRatedMoviesResponse {
    type Results = Results.Item[];
    namespace Results {
        interface Item {
            adult?: boolean;
            backdrop_path?: string;
            genre_ids?: number[];
            id?: number;
            original_language?: string;
            original_title?: string;
            overview?: string;
            popularity?: number;
            poster_path?: string;
            release_date?: string;
            title?: string;
            video?: boolean;
            vote_average?: number;
            vote_count?: number;
            account_rating?: Item.AccountRating;
        }
        namespace Item {
            interface AccountRating {
                created_at?: string;
                value?: number;
            }
        }
    }
}
