/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface AuthCreateRequestTokenResponse {
    status_message?: string;
    request_token?: string;
    success?: boolean;
    status_code?: number;
}
