/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface AuthCreateAccessTokenResponse {
    account_id?: string;
    access_token?: string;
    success?: boolean;
    status_message?: string;
    status_code?: number;
}
