/**
 * This file was auto-generated by Fern from our API Definition.
 */
export type ListItemStatusRequestMediaType = "" | "movie" | "tv";
export declare const ListItemStatusRequestMediaType: {
    readonly Empty: "";
    readonly Movie: "movie";
    readonly Tv: "tv";
};
