/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface ListDetailsResponse {
    average_rating?: number;
    backdrop_path?: string;
    results?: ListDetailsResponse.Results.Item[];
    comments?: ListDetailsResponse.Comments;
    created_by?: ListDetailsResponse.CreatedBy;
    description?: string;
    id?: number;
    iso_3166_1?: string;
    iso_639_1?: string;
    item_count?: number;
    name?: string;
    object_ids?: ListDetailsResponse.ObjectIds;
    page?: number;
    poster_path?: string;
    public?: boolean;
    revenue?: number;
    runtime?: number;
    sort_by?: string;
    total_pages?: number;
    total_results?: number;
}
export declare namespace ListDetailsResponse {
    type Results = Results.Item[];
    namespace Results {
        interface Item {
            adult?: boolean;
            backdrop_path?: string;
            id?: number;
            title?: string;
            original_language?: string;
            original_title?: string;
            overview?: string;
            poster_path?: string;
            media_type?: string;
            genre_ids?: number[];
            popularity?: number;
            release_date?: string;
            video?: boolean;
            vote_average?: number;
            vote_count?: number;
        }
    }
    interface Comments {
        "movie:617127"?: unknown;
        "movie:986056"?: unknown;
        "movie:822119"?: unknown;
        "movie:533535"?: unknown;
        "movie:609681"?: unknown;
        "movie:447365"?: unknown;
        "movie:640146"?: unknown;
        "movie:505642"?: unknown;
        "movie:616037"?: unknown;
        "movie:453395"?: unknown;
        "movie:634649"?: unknown;
        "movie:524434"?: unknown;
        "movie:566525"?: unknown;
        "movie:497698"?: unknown;
        "movie:429617"?: unknown;
        "movie:299534"?: unknown;
        "movie:299537"?: unknown;
        "movie:363088"?: unknown;
        "movie:299536"?: unknown;
        "movie:284054"?: unknown;
    }
    interface CreatedBy {
        avatar_path?: string;
        gravatar_hash?: string;
        id?: string;
        name?: string;
        username?: string;
    }
    interface ObjectIds {
    }
}
