name: Publish Ruby SDK

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Fern CLI
        run: npm install -g fern-api

      - name: Release Ruby SDK
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          fern generate --group ruby-sdk --version ${{ inputs.version }} --log-level debug