name: Publish Go SDK

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the Go spec that you would like to release"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Fern CLI
        run: npm install -g fern-api

      - name: Release Go SDK
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          fern generate --group go --version ${{ inputs.version }} --log-level debug